mqtt:
  broker: tcp://localhost:1883
  clientId: vts-mqtt-client
  username: yourUser
  password: yourPass
  topic: vehicle/+/location

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jpapractice
    username: postgres
    password: system
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect # Use the PostGIS hibernate dialect so spatial functions and types are supported
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: vts-stream-app
      default-key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default-value-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer